default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>       # データベースのユーザー名
  password: <%= ENV['DB_PASSWORD'] %>       # データベースのパスワード
  host: <%= ENV['DB_HOST'] %>               # データベースのホスト
  port: <%= ENV.fetch("DB_PORT", 3306) %>   # データベースのポート
  database: <%= ENV['DB_NAME'] %>  

development:
  <<: *default
  database: youtube

test:
  <<: *default
  database: youtube

production:
  adapter: mysql2
  encoding: utf8
  database: your_database_name
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>  # Renderのデータベースホスト名を環境変数で指定
  port: 3306 

