default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['ryusei'] %>
  password: <%= ENV['ryusei0915'] %>
  host: <%= ENV['localhost'] %>
  port: <%= ENV.fetch("DB_PORT", 3306) %>
  database: <%= ENV['youtube'] %>

development:
  <<: *default
  database: youtube

test:
  <<: *default
  database: youtube

production:
  <<: *default
  database: youtube

