default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>
  host: <%= ENV.fetch("DB_HOST") %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>  # PostgreSQLのデフォルトポートは5432
  database: <%= ENV.fetch("DB_NAME") %>

development:
  <<: *default
  database: youtube

test:
  <<: *default
  database: youtube

production:
  <<: *default
  database: youtube
